#!/bin/sh

if [[ "$1" = "1" ]]; then
	FLAGS=" -f 0,4 --export_frc 1 "
fi

if [[ ! -f enctest.avi ]]; then
	transcode -x vob,vob $FLAGS -M 2 -R 3 -w 2 -J ivtc -J decimate -B 3,9,16 --hard_fps -J 32detect=force_mode=5:chromathres=2:chromadi=9 -y xvid -o enctest.avi -A -N 0x2000 -a 0 -b 128,0,0 --write_pid transcode.pid -i $1
fi

rm transcode.pid