#!/bin/sh
# Second two pass try, with deinterlacing :D
if [[ ! -f enctest.avi ]]; then
	transcode -a 0 -b 128,0,0 -w 2200,250,100 -A -N 0x2000 -M 2 -Y 4,4,4,4 -B 1,11,8 -R 1,tc-test2.log -x vob,vob -y xvid4,null $FLAGS -o /dev/null -i $1 -I 3 -J 32detect=force_mode=5:chromathres=2:chromadi=9 --write_pid transcode.pid 
	transcode -a 0 -b 128,0,0 -w 2200,250,100 -A -N 0x2000 -M 2 -Y 4,4,4,4 -B 1,11,8 -R 2,tc-test2.log -x vob,vob -y xvid4 $FLAGS -o tc-test3.avi -i $1 -I 3 -J 32detect=force_mode=5:chromathres=2:chromadi=9 --write_pid transcode.pid
fi
rm transcode.pid