#!/bin/bash
if [[ -z "$1" ]]; then echo "Need a filename"; exit 1; fi
for video in $*; do

	# Verify file exists
	if [[ ! -e "${video}" ]]; then continue; fi

	# Skip if a directory
	if [[ -d "$video" ]]; then continue; fi

	# Get the filename variables
	video_basename="$(basename $video)"
	video_realpath="$(realpath $video)"
	video_realdir="$(dirname $video_realpath)"
	video_episode="/opt/plex/episodes/${video_basename}"
	if [[ "$video_realdir" != "/root/Library" ]]; then
		video_episode=$video_realpath
	fi
	video_library_prefix="${video_basename:0:1}"
	video_library_suffix="${video_basename:2:1}"
	video_library_type="${video_basename:17:2}"

	# Sort into its library
	if [[ "$video_library_prefix" == "1" ]]; then
		video_library="cartoons"
	elif [[ "$video_library_prefix" == "2" ]]; then
		video_library="tv"
	elif [[ "$video_library_prefix" == "3" ]]; then
		video_library="jared"
	elif [[ "$video_library_prefix" == "4" ]]; then
		video_library="movies"
	elif [[ "$video_library_prefix" == "5" ]]; then
		video_library="imax"
	elif [[ "$video_library_prefix" == "6" ]]; then
		video_library="hdtv"
	elif [[ "$video_library_prefix" == "7" ]]; then
		video_library="documentary"
	elif [[ "$video_library_prefix" == "8" ]]; then
		if [[ "$video_library_type" == "4K" ]]; then
			video_library="4k"
		else
			video_library="bluray"
		fi
	elif [[ "$video_library_prefix" == "9" ]]; then
		video_library="holiday"
	else
		echo "plex_link: library not found $video_basename"
		continue
	fi

	# Use episode_query to find what Plex directory it should be sorted into
	plex_video_dirname=`/root/bin/episode_query --dirname "$video_episode"`

	# Quit if dirname is empty, indicates that file is not in database
	if [[ "$plex_video_dirname" == "/" ]]; then echo plex_link: episode not in database - $video_basename; continue; fi

	plex_video_dirname="/opt/plex/libraries/${video_library}/$plex_video_dirname"

	# Quit if episode_query died for some reason
	if [[ $? -ne 0 ]]; then echo plex_link: episode_query --dirname $video_basename failed; continue; fi

	# Same sequence for filename
	plex_video_filename=`/root/bin/episode_query "$video_episode"`
	if [[ $? -ne 0 ]]; then echo plex_link: episode_query $video_basename failed; continue; fi

	if [[ ! -d "$plex_video_dirname" ]]; then mkdir -p "$plex_video_dirname"; fi

	if [[ ! -e "${plex_video_dirname}${plex_video_filename}" ]]; then
		ln -v -s "$video_episode" "${plex_video_dirname}${plex_video_filename}"
	fi

	# ln -v -s -f "$video_episode" "${plex_video_dirname}${plex_video_filename}"

done
