#!/bin/sh

if [[ ! -f noindex.avi ]]; then
	mencoder -ovc copy -oac copy -ofps 24000/1001 -o noindex.avi $1
fi

if [[ ! -f index.avi ]]; then
	mencoder -forceidx -ovc copy -oac copy -o index.avi $1
fi

if [[ -f noindex.avi ]]; then
	rm noindex.avi 
fi
