#!/bin/sh
# Normal 2-pass encode

if [[ ! -f tc-test1.avi ]]; then
	transcode -a 0 -b 128,0,0 -w 2200,250,100 -A -N 0x2000 -M 2 -Y 4,4,4,4 -B 1,11,8 -R 1,tc-test1.log -x vob,vob -y xvid4,null -o /dev/null --write_pid transcode.pid -i $1
	transcode -a 0 -b 128,0,0 -w 2200,250,100 -A -N 0x2000 -M 2 -Y 4,4,4,4 -B 1,11,8 -R 2,tc-test1.log -x vob,vob -y xvid4 -o tc-test1.avi --write_pid transcode.pid -i $1
fi

if [[ "$2" = "1" ]]; then
	FLAGS=" -f 0,4 --export_frc 1 -J ivtc -J decimate -J 32detect=force_mode=5:chromathres=2:chromadi=9 "
else
	FLAGS=" -J 32detect=force_mode=5:chromathres=2:chromadi=9 "
fi

# Variable framerate encode
if [[ ! -f tc-test2.avi ]]; then
	transcode -x vob,vob $FLAGS --hard_fps -M 2 -R 3 -w 2 -B 3,9,16 -y xvid -o tc-test2.avi -A -N 0x2000 -a 0 -b 128,0,0 --write_pid transcode.pid -i $1
fi

if [[ -f transcode.pid ]]; then
	rm transcode.pid
fi