#!/bin/bash
cd /home/steve/Videos/Plex
random_iso="$(/home/steve/Videos/Rip-o-Matic/wheel-o-fun)"
test -z "$random_iso" && exit
random_iso_basename="$(basename $random_iso)"
is_encoding="$(pgrep -f "HandBrakeCLI.+$random_iso_basename" -c)"
if [[ "$is_encoding" -ge 1 ]]; then echo "$random_iso_basename - DVD already being washed, spin again"; exit 1; fi

# Check to see if there are remaining episodes.
num_not_encoded=$(dvd_query -n -e -x "$random_iso")
exit_code=$?
# process dvd_query exit codes
if [[ $exit_code -eq 1 ]]; then
	echo "$random_iso_basename - dvd_query failed on processing arguments"
elif [[ $exit_code -eq 2 ]]; then
	echo "$random_iso_basename - No episodes are listed for this DVD"
	exit 1;
fi
if [[ "$num_not_encoded" -eq 0 ]]; then
	echo "$random_iso_basename - DVD already encoded, spin again"
	exit 1
fi

random_iso_log="/home/steve/Videos/Rip-o-Matic/catch-alot/$random_iso_basename.log"
touch "$random_iso_log"
dvd_query -e -x "$random_iso"
if [[ $? -ne 0 ]]; then echo "dvd_query failed, exiting"; exit 1; fi
encode_script="$(basename $random_iso_basename .iso).sh"
/home/steve/bin/dvd_encode_script "$random_iso"
if [[ ! -e "$encode_script" ]]; then echo "no encode script created, exiting"; exit 1; fi
mv $encode_script /home/steve/Videos/Rip-o-Matic/bulky-bottles/
echo "[ `date` - $random_iso_basename ] - Wish-Wash, Encode Starting :)" >> /home/steve/Videos/Rip-o-Matic/event.log
cd /home/steve/Videos/Rip-o-Matic/bulky-bottles
ln -sf "$random_iso" .
cd ~/Videos/Plex
/home/steve/Videos/Rip-o-Matic/bulky-bottles/$encode_script 2> "$random_iso_log" | tee -a "$random_iso_log"
echo "[ `date` - $random_iso_basename ] - Fluff-Puff, Encode Finished :D" >> /home/steve/Videos/Rip-o-Matic/event.log
echo "$random_iso can be safely removed" >> /home/steve/Videos/Rip-o-Matic/event.log
