#!/bin/bash

# tobe
# /dev/sr0 - LG Blu-ray - disc:1
# /dev/sr1 - ASUS Blu-ray - disc:0

device="$1"
if [[ -z "$1" ]]; then device=/dev/sr0; fi

dvd_drive_status $device
if [[ $? -ne 4 ]]; then exit 1; fi

disc_type=`disc_type $device`
if [[ "$disc_type" != "bluray" ]]; then
	echo disc type is $disc_type
	# exit 1
fi

if [[ "$device" == "/dev/sr0" ]]; then disc=0; fi
if [[ "$device" == "/dev/sr1" ]]; then disc=1; fi
if [[ "$device" == "/dev/sr2" ]]; then disc=2; fi
if [[ "$device" == "/dev/sr3" ]]; then disc=3; fi

pgrep -c -f disc:$disc &> /dev/null
if [[ $? -eq 0 ]]; then
	echo "makemkvcon already running on $device"
	exit 1
fi

makemkvcon --noscan --minlength=0 --robot backup --decrypt disc:${disc} .
