#!/bin/bash
EXIT_CODE=1
DEVICE=$1
if [[ -z $DEVICE ]]; then
	DEVICE=/dev/dvd
fi

if [[ ! -b $DEVICE ]]; then
	echo "Device $DEVICE doesn't exist" >&2
	exit 1
fi

while [[ $EXIT_CODE != 0 ]]; do
	/usr/local/bin/disc_id $DEVICE 2> /dev/null
	EXIT_CODE=$?

	if [[ $EXIT_CODE != 0 ]]; then
		sleep 1
	fi
done
