#!/bin/sh
FILE=`basename $1 .mkv`
SCREENSHOT=${FILE}.jpg
mplayer "$1" -vo jpeg -sb 40819594 -frames 5 -vf scale=360:240 -ao null -quiet -really-quiet 2> /dev/null
mv 00000005.jpg $SCREENSHOT
rm 0000000{1,2,3,4}.jpg
